import type { SidebarsConfig } from "@docusaurus/plugin-content-docs";

const sidebars: SidebarsConfig = {
  docs: [
    {
      type: "category",
      label: "📊 Executive Documentation",
      collapsed: false,
      items: [
        "executive/executive-summary",
        "executive/investor-executive-summary",
        "executive/global-strategy",
        "executive/system-overview",
        "executive/system-overview-detailed",
        "executive/team-status",
        "executive/strategic-recommendations",
        "executive/key-questions-cheatsheet",
        "executive/presentation-materials",
        "executive/phoenix-rooivalk-litepaper",
        "executive/phoenix-rooivalk-pitch-deck",
        "executive/phoenix-rooivalk-technical-whitepaper",
        {
          type: "category",
          label: "Early Development",
          collapsed: true,
          items: ["executive/early-development/early-spec-qa"],
        },
      ],
    },
    {
      type: "category",
      label: "🔧 Technical Documentation",
      collapsed: false,
      items: [
        "technical/technical-architecture",
        "technical/system-architecture",
        "technical/blockchain-integration",
        "technical/multi-user-signing-cooperation",
        "technical/decentralized-ai",
        "technical/hardware-foundation",
        "technical/defense-integration",
        "technical/defense-technology-deep-dive",
        "technical/ai-benefits",
        "technical/glossary",
        "technical/technical-analysis",
        "technical/technical-architecture-synthesis",
        "technical/threatsimulator-enhancements",
        {
          type: "category",
          label: "Architecture",
          collapsed: true,
          items: [
            "technical/architecture/technical-architecture",
            "technical/architecture/architecture-decision-records",
          ],
        },
        {
          type: "category",
          label: "Blockchain",
          collapsed: true,
          items: [
            "technical/blockchain/blockchain-architecture",
            "technical/blockchain/blockchain-architecture-detailed",
            "technical/blockchain/blockchain-benefits",
            "technical/blockchain/blockchain-implementation-guide",
            "technical/blockchain/blockchain-implementation-phases",
            "technical/blockchain/blockchain-protocols-analysis",
            "technical/blockchain/blockchain-security-compliance",
            "technical/blockchain/implementation-roadmap",
          ],
        },
        {
          type: "category",
          label: "Integration",
          collapsed: true,
          items: [
            "technical/integration/api-documentation",
            "technical/integration/integration-guide",
          ],
        },
        {
          type: "category",
          label: "Mechanical",
          collapsed: true,
          items: [
            "technical/mechanical/mechanical-design-adrs",
            "technical/mechanical/mechanical-design-records",
          ],
        },
        {
          type: "category",
          label: "Hardware",
          collapsed: true,
          items: [
            "technical/hardware/rkv-m-specifications",
            "technical/hardware/net-specifications",
          ],
        },
        {
          type: "category",
          label: "ML Training",
          collapsed: true,
          items: [
            "technical/ml-training/ml-training-plan",
            "technical/ml-training/drone-training-data-sources",
          ],
        },
        {
          type: "category",
          label: "Performance",
          collapsed: true,
          items: ["technical/performance/performance-specifications"],
        },
      ],
    },
    {
      type: "category",
      label: "💼 Business Documentation",
      collapsed: false,
      items: [
        "business/market-analysis",
        "business/business-model",
        "business/12-month-business-plan",
        "business/competitive-analysis",
        "business/emerging-trends",
        "business/roi-analysis",
        "business/use-cases",
        "business/budget-timeline-templates",
        "business/commercial-proposal-template",
        "business/competitive-differentiation-guide",
        "business/discovery-questionnaire",
        "business/dod-proposal-template",
        "business/presentation-video-script",
        "business/technical-requirements-checklist",
        "business/traction-metrics",
        "business/influencers-and-contacts",
        {
          type: "category",
          label: "Opportunities",
          collapsed: true,
          items: [
            "business/opportunities/opportunities-summary",
            "business/opportunities/soonami-cohort-8",
            "business/opportunities/cuas-sandbox-2026",
          ],
        },
        {
          type: "category",
          label: "Applications",
          collapsed: true,
          items: ["business/applications/cuas-sandbox-2026-application"],
        },
      ],
    },
    {
      type: "category",
      label: "⚖️ Legal Documentation",
      collapsed: false,
      items: ["legal/compliance-framework", "legal/legal-framework"],
    },
    {
      type: "category",
      label: "🚀 Operations Documentation",
      collapsed: false,
      items: [
        "operations/manufacturing-strategy",
        "operations/operational-resilience",
        "operations/implementation-plan",
        "operations/operations-manual",
        "operations/operations-modes",
        "operations/customer-onboarding-guide",
        {
          type: "category",
          label: "Deployment",
          collapsed: true,
          items: ["operations/deployment/deployment-guide"],
        },
        {
          type: "category",
          label: "Maintenance",
          collapsed: true,
          items: ["operations/maintenance/maintenance-procedures"],
        },
        {
          type: "category",
          label: "Monitoring",
          collapsed: true,
          items: [
            "operations/monitoring/operations-log-template",
            "operations/monitoring/troubleshooting-guide",
          ],
        },
        {
          type: "category",
          label: "Training",
          collapsed: true,
          items: ["operations/training/training-materials"],
        },
        {
          type: "category",
          label: "Calendar",
          collapsed: true,
          items: ["operations/calendar/project-calendar"],
        },
      ],
    },
    {
      type: "category",
      label: "🎨 Design Documentation",
      collapsed: false,
      items: ["design/icon-requirements"],
    },
    {
      type: "category",
      label: "📊 Visual Elements",
      collapsed: false,
      items: ["visual-elements/system-architecture-diagrams"],
    },
    {
      type: "category",
      label: "🔬 Research Documentation",
      collapsed: false,
      items: [
        "research/experimental-counter-drone-effectors-transform-warfare",
        "research/sensor-technologies-comprehensive-analysis",
      ],
    },
    {
      type: "category",
      label: "📚 Resources & References",
      collapsed: false,
      items: ["resources/downloads", "resources/suas-program-documentation"],
    },
  ],
};

export default sidebars;
