# Conda environment for Azure ML training
# This file is used by Azure ML to create the training environment
#
# Usage:
#   # Create locally for testing
#   conda env create -f conda.yaml
#   conda activate drone-detection
#
#   # Azure ML uses this automatically via job.yaml

name: drone-detection

channels:
  - pytorch
  - conda-forge
  - defaults

dependencies:
  - python=3.10
  - pip>=23.0

  # PyTorch with CUDA support (Azure ML provides CUDA runtime)
  - pytorch>=2.0.0,<3.0.0
  - torchvision>=0.15.0,<1.0.0
  - pytorch-cuda=11.8

  - pip:
      # Ultralytics YOLO (main training framework)
      - ultralytics>=8.0.0,<9.0.0

      # Computer vision
      - opencv-python-headless>=4.8.0,<5.0.0

      # Data processing
      - numpy>=1.24.0,<2.0.0
      - pillow>=9.5.0,<11.0.0
      - pyyaml>=6.0
      - pandas>=2.0.0,<3.0.0

      # Visualization & monitoring
      - matplotlib>=3.7.0,<4.0.0
      - seaborn>=0.12.0,<1.0.0
      - tqdm>=4.65.0

      # Scientific computing
      - scipy>=1.10.0,<2.0.0

      # Model export formats
      - onnx>=1.14.0,<2.0.0
      - onnxruntime>=1.15.0,<2.0.0
      - onnxsim>=0.4.0  # ONNX simplifier

      # TensorFlow for TFLite export
      # Version >= 2.13.1 required for CVE-2024-3660 fix
      # Version < 2.16 for compatibility with ultralytics export
      - tensorflow>=2.13.1,<2.16.0

      # Azure ML SDK (for logging and artifact tracking)
      - azureml-mlflow>=1.50.0
      - mlflow>=2.0.0,<3.0.0

      # Utilities
      - psutil>=5.9.0
